
/**************************************************************
 *	
 *	dodgingSound, 8 bit, 11025Hz,
 *	1 channel, 38789 bytes/channel
 *	Total Size: 1 * 38789 + 4 (header) = 39073 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Owner\Documents\Fall_2015\CS 2261\FinalProject\dodgingSound.wav
 *	Time-stamp: Tue Nov 10 19:24:16 2015
 *	
 **************************************************************/

#ifndef __DODGINGSOUNDH__
#define __DODGINGSOUNDH__

#define DODGINGSOUNDFREQ 11025
#define DODGINGSOUNDLEN 38789

extern const unsigned char dodgingSound[38789];

#endif /* __DODGINGSOUNDH__ */
