
/**************************************************************
 *	
 *	missionImpossible, 8 bit, 11025Hz,
 *	1 channel, 773719 bytes/channel
 *	Total Size: 1 * 773719 + 4 (header) = 774003 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Owner\Documents\Fall_2015\CS 2261\FinalProject\missionImpossible.wav
 *	Time-stamp: Tue Nov 10 19:12:58 2015
 *	
 **************************************************************/

#ifndef __MISSIONIMPOSSIBLEH__
#define __MISSIONIMPOSSIBLEH__

#define MISSIONIMPOSSIBLEFREQ 11025
#define MISSIONIMPOSSIBLELEN 773719

extern const unsigned char missionImpossible[773719];

#endif /* __MISSIONIMPOSSIBLEH__ */
